# Generated by Django 2.2.4 on 2019-10-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contactno', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
